language: python
python:
    - "2.7"
env:
  - NUMBA_DISABLE_JIT=1

before_install:
    - sudo apt-get update
    - sudo apt-get install python-pyqt5
    - pip install coveralls
    - pip install pytest-qt
    - pip install pytest-xvfb

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - coverage run --source hmmsort -m py.test -s -q

after_success:
    - coverage report
    - coveralls
