language: python
python: 
    - "2.7"
before_install:
    - pip install coveralls
install: 
    - pip install -r requirements.txt
    - pip install .

script: 
    - coverage run --source hmmsort -m py.test

after_success:
    - coverage report
    - coveralls
